### PR TITLE
fix event.ID && event.ResourceID name bug

### PR DESCRIPTION
**Pull request by scofieldpeng**
rancherevents/util/util.go line 11 and 13

### CODE REVIEW

**Comment by alena1108** [comment]
@scofieldpeng this change would require go-machine-service vendor update. Current version is https://github.com/rancher/go-machine-service/commits/3c74782bf970723228c399950d84f10764c3a47c

**Comment by scofieldpeng** [comment]
@alena1108  ok,and do you mind to tell me the dependency tool this project use please? I see the empty directories under the vendor after i clone it the my local machine and have to do more jobs to make it run, tks :-)

**Comment by alena1108** [comment]
You can find the information about deps here:

https://github.com/rancher/kubernetes-agent/blob/master/.gitmodules

**Comment by ibuildthecloud** [comment]
@scofieldpeng This project uses git submodules, but we are deleting them and switch to [trash](https://github.com/rancher/trash) for vendor managment.

**Comment by ibuildthecloud** [comment]
By somewhat of a coincidence, https://github.com/rancher/kubernetes-agent/pull/17 address this change.

**Pull request closed without merging**
